version: "3"
services: 
  portfolyo-builder:
    build: .
    env_file:
      - ./.env
    networks:
      - portfolyo-network
  nginx:
    image: nginx:mainline-alpine
    ports: 
      - "443:443"
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - portfolyo-builder
    networks:
      - portfolyo-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email 19h51a05g2@cmrcet.ac.in --agree-tos --no-eff-email --staging -d portfolyo.systems -d www.portfolyo.systems
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind

networks:
  portfolyo-network:
    driver: bridge