version: "3"
services: 
  portfolyo-builder:
    image: akshaymurari0/portfolyo
    command: npm run start
    volumes:
      - ./controllers/resume:/app/controllers/resume
    deploy:
      mode: replicated
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 10s
