version: "3"
services: 
  nginx:
    image: nginx:alpine
    ports: 
      - "443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  portfolyo-builder:
    build: .
    env_file:
      - ./.env