version: "3"
services: 
  portfolyo-builder:
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 2